spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/group_purchase?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    #username: root
    #password: 12345678
    username: group_purchase
    password: zK75tPdzX3fitMrx
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 123456
    database: 3

# 图片上传配置
upload-config:
  type: 1 # 1=本地上传, 2=云端上传
  path: /java/shopgroup/images/public # 本地路径公有文件上传路径
  path2: /java/shopgroup/images/private # 本地路径私有文件上传路径
  domain: https://test.shopgroup.com.cn/image # 公有文件访问域名
  domain2: https://test.shopgroup.com.cn/image/access # 私有文件访问域名

# 易宝支付回调
pay-config:
  url: https://test.shopgroup.com.cn/group/order/notify
