spring:
  servlet:
    multipart:
      # Spring单个文件上传限制大小
      max-file-size : 5MB
      # Spring单个请求限制大小
      max-request-size : 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/group_purchase?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    #username: root
    #password: 12345678
    username: group_purchase
    password: zK75tPdzX3fitMrx
    # Druid 连接池核心配置
    druid:
      # 空闲连接检测间隔（毫秒）, 建议小于MySQL wait_timeout, 默认值：60000 毫秒 = 60 秒
      time-between-eviction-runs-millis: 60000
      # 空闲连接最小存活时间, 默认值：1800000 毫秒 = 30 分钟, 这里设置的是10分钟
      # 超过该阈值，Druid 就会校验并丢弃无效连接
      min-evictable-idle-time-millis: 600000
      # 检测空闲连接时执行的校验SQL
      validation-query: SELECT 1
      # 空闲时是否执行校验SQL, 解决断连警告必须改为 true
      test-while-idle: true
      # 获取连接时不校验（影响性能，默认false）
      test-on-borrow: false
      # 归还连接时不校验（影响性能，默认false）
      test-on-return: false
      # 初始化连接数（默认0）
      initial-size: 100
      # 最小空闲连接数（默认5）
      min-idle: 100
      # 最大活跃连接数（默认8）
      max-active: 500
      # 获取连接的最大等待时间（默认-1，无限制）
      max-wait: 5000
      # 关闭Druid监控统计功能
      stat-view-servlet:
        enabled: false
      # 关闭Web应用监控
      web-stat-filter:
        enabled: false
      # 使用过滤器
      filter:
        # 关闭慢SQL记录
        stat:
          enabled: false
        # 开启SQL防火墙
        wall:
          enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    #username: xxxxxxxxxxx
    ###password: 12345678
    database: 1

# 图片上传配置
upload-config:
  type: 1 # 1=本地上传, 2=云端上传
  path: /java/shopgroup/images/public # 本地路径公有文件上传路径
  path2: /java/shopgroup/images/private # 本地路径私有文件上传路径
  domain: https://test.shopgroup.com.cn/image # 公有文件访问域名
  domain2: https://test.shopgroup.com.cn/image/access # 私有文件访问域名


